# Generated by Django 4.1.1 on 2022-09-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productUpdatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
