# Generated by Django 4.1.1 on 2022-09-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_oderproduct_order_orderproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
